<upgrade>
	<phrases>
		<phrase>
			<module_id>search</module_id>
			<version_id>2.0.7</version_id>
			<var_name>user_setting_can_use_global_search</var_name>
			<added>1288616524</added>
			<value>Can use the global search tool?</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>search</module_id>
			<type>boolean</type>
			<admin>1</admin>
			<user>1</user>
			<guest>1</guest>
			<staff>1</staff>
			<module>search</module>
			<ordering>0</ordering>
			<value>can_use_global_search</value>
		</setting>
	</user_group_settings>
</upgrade>