<upgrade>
	<phrases>
		<phrase>
			<module_id>custom</module_id>
			<version_id>2.0.5</version_id>
			<var_name>submit</var_name>
			<added>1273137049</added>
			<value>Submit</value>
		</phrase>
	</phrases>
	<hooks>
		<hook>
			<module_id>custom</module_id>
			<hook_type>component</hook_type>
			<module>custom</module>
			<call_name>custom.component_ajax_edit</call_name>
			<added>1274286148</added>
			<version_id>2.0.5dev1</version_id>
			<value />
		</hook>
	</hooks>
</upgrade>