<upgrade>
	<phrases>
		<phrase>
			<module_id>user</module_id>
			<version_id>3.4.0rc1</version_id>
			<var_name>user_setting_can_purchase_with_points</var_name>
			<added>1349939638</added>
			<value>Can purchase with activity points?</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>user</module_id>
			<type>boolean</type>
			<admin>1</admin>
			<user>1</user>
			<guest>0</guest>
			<staff>1</staff>
			<module>user</module>
			<ordering>0</ordering>
			<value>can_purchase_with_points</value>
		</setting>
	</user_group_settings>
</upgrade>