<upgrade>
	<phrases>
		<phrase>
			<module_id>marketplace</module_id>
			<version_id>2.0.0rc8</version_id>
			<var_name>category</var_name>
			<added>1258986746</added>
			<value>Category</value>
		</phrase>
		<phrase>
			<module_id>marketplace</module_id>
			<version_id>2.0.0rc8</version_id>
			<var_name>update</var_name>
			<added>1258986799</added>
			<value>Update</value>
		</phrase>
		<phrase>
			<module_id>marketplace</module_id>
			<version_id>2.0.0rc8</version_id>
			<var_name>cancel</var_name>
			<added>1258986813</added>
			<value>Cancel</value>
		</phrase>
	</phrases>
	<update_templates>
		<file type="controller">add.html.php</file>
	</update_templates>
</upgrade>