<upgrade>
	<phpfox_update_phrases>
		<phrase>
			<module_id>marketplace</module_id>
			<version_id>3.3.0beta1</version_id>
			<var_name>visted</var_name>
			<added>1339155389</added>
			<value>Visited</value>
		</phrase>
	</phpfox_update_phrases>
</upgrade>