<upgrade>
	<phrases>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>no_more_search_results_to_show</var_name>
			<added>1322738857</added>
			<value>No more search results to show.</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>no_search_results_found</var_name>
			<added>1322738868</added>
			<value>No search results found.</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>view_more</var_name>
			<added>1322738882</added>
			<value>View More</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>all_results</var_name>
			<added>1323335939</added>
			<value>All Results</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>poll</var_name>
			<added>1323336059</added>
			<value>Poll</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>members</var_name>
			<added>1323336072</added>
			<value>Members</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>videos</var_name>
			<added>1323336086</added>
			<value>Videos</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>video</var_name>
			<added>1323336092</added>
			<value>Video</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>listings</var_name>
			<added>1323336105</added>
			<value>Listings</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>marketplace_listing</var_name>
			<added>1323336112</added>
			<value>Marketplace Listing</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>songs</var_name>
			<added>1323336131</added>
			<value>Songs</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>song</var_name>
			<added>1323336136</added>
			<value>Song</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>photos</var_name>
			<added>1323336144</added>
			<value>Photos</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>photo</var_name>
			<added>1323336151</added>
			<value>Photo</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>quizzes</var_name>
			<added>1323336160</added>
			<value>Quizzes</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>quiz</var_name>
			<added>1323336165</added>
			<value>Quiz</value>
		</phrase>
		<phrase>
			<module_id>search</module_id>
			<version_id>3.0.0</version_id>
			<var_name>forum_thread</var_name>
			<added>1323336176</added>
			<value>Forum Thread</value>
		</phrase>
	</phrases>
</upgrade>