<upgrade>
	<phrases>
		<phrase>
			<module_id>marketplace</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>loading</var_name>
			<added>1320324900</added>
			<value>Loading...</value>
		</phrase>
		<phrase>
			<module_id>marketplace</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>close</var_name>
			<added>1320324906</added>
			<value>Close</value>
		</phrase>
		<phrase>
			<module_id>marketplace</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>more_from_seller</var_name>
			<added>1320324937</added>
			<value>More From Seller</value>
		</phrase>
	</phrases>
	<hooks>
		<hook>
			<module_id>marketplace</module_id>
			<hook_type>component</hook_type>
			<module>marketplace</module>
			<call_name>marketplace.component_block_featured_clean</call_name>
			<added>1319729453</added>
			<version_id>3.0.0rc1</version_id>
			<value />
		</hook>
		<hook>
			<module_id>marketplace</module_id>
			<hook_type>component</hook_type>
			<module>marketplace</module>
			<call_name>marketplace.component_block_invite_clean</call_name>
			<added>1319729453</added>
			<version_id>3.0.0rc1</version_id>
			<value />
		</hook>
		<hook>
			<module_id>marketplace</module_id>
			<hook_type>component</hook_type>
			<module>marketplace</module>
			<call_name>marketplace.component_block_price_clean</call_name>
			<added>1319729453</added>
			<version_id>3.0.0rc1</version_id>
			<value />
		</hook>
	</hooks>
</upgrade>