<upgrade>
	<phrases>
		<phrase>
			<module_id>photo</module_id>
			<version_id>2.0.3</version_id>
			<var_name>user_setting_can_post_on_photos</var_name>
			<added>1264423442</added>
			<value>Can post comments on photos?</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>photo</module_id>
			<type>boolean</type>
			<admin>1</admin>
			<user>1</user>
			<guest>0</guest>
			<staff>1</staff>
			<module>photo</module>
			<ordering>0</ordering>
			<value>can_post_on_photos</value>
		</setting>
	</user_group_settings>
</upgrade>