<upgrade>
	<phrases>
		<phrase>
			<module_id>photo</module_id>
			<version_id>2.1.0beta2</version_id>
			<var_name>user_setting_total_photo_display_profile</var_name>
			<added>1300968617</added>
			<value>Define how many photos to display within an album on a users profile.</value>
		</phrase>
		<phrase>
			<module_id>photo</module_id>
			<version_id>2.1.0beta2</version_id>
			<var_name>album_successfully_created</var_name>
			<added>1300969620</added>
			<value>Album successfully created.</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>photo</module_id>
			<type>integer</type>
			<admin>9</admin>
			<user>9</user>
			<guest>9</guest>
			<staff>9</staff>
			<module>photo</module>
			<ordering>0</ordering>
			<value>total_photo_display_profile</value>
		</setting>
	</user_group_settings>
</upgrade>