<upgrade>
	<phrases>
		<phrase>
			<module_id>feed</module_id>
			<version_id>3.7.0beta1</version_id>
			<var_name>user_setting_feed_sponsor_price</var_name>
			<added>1374735438</added>
			<value>How much does it cost to sponsor a feed post? This works in a CPM basis</value>
		</phrase>
		<phrase>
			<module_id>feed</module_id>
			<version_id>3.7.0beta1</version_id>
			<var_name>user_setting_can_sponsor_feed</var_name>
			<added>1374837851</added>
			<value>Can members of this user group define a feed as sponsored without paying?</value>
		</phrase>
		<phrase>
			<module_id>feed</module_id>
			<version_id>3.7.0beta1</version_id>
			<var_name>user_setting_auto_publish_sponsored_item</var_name>
			<added>1374837880</added>
			<value>Should sponsored items be published right away?</value>
		</phrase>
		<phrase>
			<module_id>feed</module_id>
			<version_id>3.7.0beta1</version_id>
			<var_name>user_setting_can_sponsor_feeds</var_name>
			<added>1375264862</added>
			<value>Can members of this user group sponsor feeds?</value>
		</phrase>
		<phrase>
			<module_id>feed</module_id>
			<version_id>3.7.0beta1</version_id>
			<var_name>sponsor_in_feed</var_name>
			<added>1375265039</added>
			<value>Sponsor In Feed</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>string</type>
			<admin>0</admin>
			<user>0</user>
			<guest>999999</guest>
			<staff>0</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>feed_sponsor_price</value>
		</setting>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>boolean</type>
			<admin>true</admin>
			<user>false</user>
			<guest>false</guest>
			<staff>false</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>can_sponsor_feed</value>
		</setting>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>boolean</type>
			<admin>true</admin>
			<user>true</user>
			<guest>true</guest>
			<staff>true</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>auto_publish_sponsored_item</value>
		</setting>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>boolean</type>
			<admin>false</admin>
			<user>false</user>
			<guest>false</guest>
			<staff>false</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>can_sponsor_feeds</value>
		</setting>
	</user_group_settings>
</upgrade>