<upgrade>
	<phrases>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>select_a_banner_type</var_name>
			<added>1252753837</added>
			<value>Select a banner type.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>provide_a_name_for_this_campaign</var_name>
			<added>1252753852</added>
			<value>Provide a name for this campaign.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>provide_a_link_for_your_banner</var_name>
			<added>1252753867</added>
			<value>Provide a link for your banner.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>provide_html_for_your_banner</var_name>
			<added>1252753880</added>
			<value>Provide HTML for your banner.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ad_successfully_updated</var_name>
			<added>1252753898</added>
			<value>Ad successfully updated.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ad_successfully_added</var_name>
			<added>1252753912</added>
			<value>Ad successfully added.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>create_new_campaign</var_name>
			<added>1252753952</added>
			<value>Create New Campaign</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ad_successfully_deleted</var_name>
			<added>1252753984</added>
			<value>Ad successfully deleted.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ad_s_successfully_updated</var_name>
			<added>1252753996</added>
			<value>Ad(s) successfully updated.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>manage_ad_campaigns</var_name>
			<added>1252754009</added>
			<value>Manage Ad Campaigns</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>live</var_name>
			<added>1252754044</added>
			<value>Live</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>inactive</var_name>
			<added>1252754056</added>
			<value>Inactive</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>pending</var_name>
			<added>1252754087</added>
			<value>Pending</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>the_ad_you_are_looking_for_does_not_exist</var_name>
			<added>1252754114</added>
			<value>The ad you are looking for does not exist.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>unable_to_find_this_ad</var_name>
			<added>1252754128</added>
			<value>Unable to find this ad.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>unable_to_find_the_ad_you_want_to_delete</var_name>
			<added>1252754169</added>
			<value>Unable to find the ad you want to delete.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>media</var_name>
			<added>1252754277</added>
			<value>Media</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>banner_type</var_name>
			<added>1252754868</added>
			<value>Banner Type</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>image</var_name>
			<added>1252755783</added>
			<value>Image</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>html</var_name>
			<added>1252755791</added>
			<value>HTML</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>banner_image</var_name>
			<added>1252755809</added>
			<value>Banner Image</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>click_here_to_change_this_banner_image</var_name>
			<added>1252755843</added>
			<value><![CDATA[Click <a href="#" onclick="$('#js_ad_upload_banner').show(); $('#js_ad_banner').hide(); return false;">here</a> to change this banner image.]]></value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>you_can_upload_a_jpg_gif_or_png_file</var_name>
			<added>1252755856</added>
			<value>You can upload a JPG, GIF or PNG file.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>cancel</var_name>
			<added>1252755868</added>
			<value>cancel</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>banner_link</var_name>
			<added>1252755962</added>
			<value>Banner Link</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>campaign_details</var_name>
			<added>1252755974</added>
			<value>Campaign Details</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>campaign_name</var_name>
			<added>1252755984</added>
			<value>Campaign Name</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>start_date</var_name>
			<added>1252755996</added>
			<value>Start Date</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>end_date</var_name>
			<added>1252756009</added>
			<value>End Date</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>do_not_end_this_campaign</var_name>
			<added>1252756023</added>
			<value>Do not end this campaign.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>end_on_a_specific_date</var_name>
			<added>1252756033</added>
			<value>End on a specific date.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>total_views</var_name>
			<added>1252756046</added>
			<value>Total Views</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>unlimited</var_name>
			<added>1252756064</added>
			<value>Unlimited</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>total_clicks</var_name>
			<added>1252756100</added>
			<value>Total Clicks</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>active</var_name>
			<added>1252756118</added>
			<value>Active</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>placement</var_name>
			<added>1252756132</added>
			<value>Placement</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>block_placement</var_name>
			<added>1252756143</added>
			<value>Block Placement</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>view_site_layout</var_name>
			<added>1252756155</added>
			<value>View Site Layout</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>notice_the_ad_sizes_provided_is_a_recommendation</var_name>
			<added>1252756164</added>
			<value>Notice: The ad sizes provided is a recommendation.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>audience</var_name>
			<added>1252756171</added>
			<value>Audience</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>user_groups</var_name>
			<added>1252756180</added>
			<value>User Groups</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>all_user_groups</var_name>
			<added>1252756189</added>
			<value>All User Groups</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>selected_user_groups</var_name>
			<added>1252756197</added>
			<value>Selected User Groups</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>location</var_name>
			<added>1252756209</added>
			<value>Location</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>gender</var_name>
			<added>1252756218</added>
			<value>Gender</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>age_group_between</var_name>
			<added>1252756226</added>
			<value>Age Group Between</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>any</var_name>
			<added>1252756234</added>
			<value>Any</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>min_age_cannot_be_higher_than_max_age</var_name>
			<added>1252756315</added>
			<value>Min age cannot be higher than max age.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>max_age_cannot_be_lower_than_the_min_age</var_name>
			<added>1252756568</added>
			<value>Max age cannot be lower than the Min age.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ads</var_name>
			<added>1252756602</added>
			<value>Ads</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>id</var_name>
			<added>1252756610</added>
			<value>ID</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>name</var_name>
			<added>1252756618</added>
			<value>Name</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>status</var_name>
			<added>1252756626</added>
			<value>Status</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>views</var_name>
			<added>1252756642</added>
			<value>Views</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>clicks</var_name>
			<added>1252756682</added>
			<value>Clicks</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>edit</var_name>
			<added>1252756691</added>
			<value>Edit</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>delete</var_name>
			<added>1252756699</added>
			<value>Delete</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>no_ads_have_been_created</var_name>
			<added>1252756733</added>
			<value>No ads have been created.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>add_a_new_add</var_name>
			<added>1252756768</added>
			<value>Add a New Add</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>cache_manager</var_name>
			<added>1252757546</added>
			<value>Cache Manager</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>note_the_time_is_set_to_your_registered_time_zone</var_name>
			<added>1253448407</added>
			<value>Note the time is set to your registered time zone.</value>
		</phrase>
	</phrases>
</upgrade>