<upgrade>
	<phrases>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>delete_all_notifications</var_name>
			<added>1321287473</added>
			<value>Delete All Notifications</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>delete_this_notification</var_name>
			<added>1321287483</added>
			<value>Delete this notification</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>reset_notification_count</var_name>
			<added>1321288351</added>
			<value>Reset Notification Count</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>today</var_name>
			<added>1321288827</added>
			<value>Today</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>yesterday</var_name>
			<added>1321288834</added>
			<value>Yesterday</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>you</var_name>
			<added>1321288853</added>
			<value>You</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>and</var_name>
			<added>1321288864</added>
			<value>and</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>other</var_name>
			<added>1321288891</added>
			<value>other</value>
		</phrase>
		<phrase>
			<module_id>notification</module_id>
			<version_id>3.0.0rc1</version_id>
			<var_name>others</var_name>
			<added>1321288918</added>
			<value>others</value>
		</phrase>
	</phrases>
</upgrade>