<upgrade>
	<phrases>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>enabled</var_name>
			<added>1319184231</added>
			<value>Enabled</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>disabled</var_name>
			<added>1319184236</added>
			<value>Disabled</value>
		</phrase>
	</phrases>
</upgrade>