<upgrade>
	<phrases>
		<phrase>
			<module_id>forum</module_id>
			<version_id>3.0.0rc2</version_id>
			<var_name>approve</var_name>
			<added>1321360256</added>
			<value>Approve</value>
		</phrase>
	</phrases>
</upgrade>