<upgrade>
	<phrases>
		<phrase>
			<module_id>attachment</module_id>
			<version_id>3.3.0beta2</version_id>
			<var_name>converting</var_name>
			<added>1340964309</added>
			<value>Converting</value>
		</phrase>
	</phrases>
</upgrade>