
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your blog. -->
<!-- It contains information about your blog's posts, comments, and categories. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your blog. -->

<!-- To import this information into a WordPress blog follow these steps. -->
<!-- 1. Log in to that blog as an administrator. -->
<!-- 2. Go to Tools: Import in the blog's admin panels (or Manage: Import in older versions of WordPress). -->
<!-- 3. Choose "WordPress" from the list. -->
<!-- 4. Upload this file using the form provided on that page. -->
<!-- 5. You will first be asked to map the authors in this export file to users -->
<!--    on the blog.  For each author, you may choose to map to an -->
<!--    existing user on the blog or to create a new user -->
<!-- 6. WordPress will then import each of the posts, comments, and categories -->
<!--    contained in this file into your blog -->

<!-- generator="WordPress.com" created="2011-04-26 08:16"-->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.0/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.0/"
>

<channel>
	<title>testing</title>
	<link>http://linhhv.wordpress.com</link>
	<description>Just another WordPress.com site</description>
	<pubDate>Tue, 26 Apr 2011 08:16:02 +0000</pubDate>
	<generator>http://wordpress.org/?v=MU</generator>
	<language>en</language>
	<wp:wxr_version>1.0</wp:wxr_version>
	<wp:base_site_url>http://wordpress.com/</wp:base_site_url>
	<wp:base_blog_url>http://linhhv.wordpress.com</wp:base_blog_url>
	{*template file='core.block.category'*}
	{foreach from=$categories item=aCategory}
		<wp:category><wp:category_nicename>{$aCategory.name}</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[{$aCategory.name}]]></wp:cat_name></wp:category>
	{/foreach}
	<generator>http://wordpress.com/</generator>
<cloud domain='linhhv.wordpress.com' port='80' path='/?rsscloud=notify' registerProcedure='' protocol='http-post' />
	<image>
		<url>http://s2.wp.com/i/buttonw-com.png</url>
		<title>testing</title>
		<link>http://linhhv.wordpress.com</link>
	</image>
	<atom:link rel="search" type="application/opensearchdescription+xml" href="http://{$username}.wordpress.com/osd.xml" title="testing" />
	<atom:link rel='hub' href='http://{$username}.wordpress.com/?pushpress=hub'/>
	{foreach from=$aItems item=aItem}
		<item>
		<title>{$aItem.title}</title>
		<link>http://{$username}.wordpress.com/2011/04/26/{$aItem.title_url}/</link>
		<pubDate>{$aItem.pub_date}</pubDate>
		<dc:creator><![CDATA[{$username}]]></dc:creator>

		{foreach from=$aItem.category_name item=cat}
		<category><![CDATA[{$cat.name}]]></category>
		<category domain="category" nicename="{$cat.name}"><![CDATA[{$cat.name}]]></category>
		{/foreach}

		<guid isPermaLink="false">http://{$username}.wordpress.com/?p={$aItem.blog_id}</guid>
		<description></description>
		<content:encoded><![CDATA[{$aItem.text}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>{$aItem.blog_id}</wp:post_id>
		<wp:post_date>{$aItem.post_date}</wp:post_date>
		<wp:post_date_gmt>{$aItem.post_date}</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>{$aItem.title_url}</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>post</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
								<wp:postmeta>
		<wp:meta_key>_edit_last</wp:meta_key>
		<wp:meta_value><![CDATA[{$aItem.time_stamp}]]></wp:meta_value>
		</wp:postmeta>
				<wp:postmeta>
		<wp:meta_key>jabber_published</wp:meta_key>
		<wp:meta_value><![CDATA[{$aItem.time_stamp}]]></wp:meta_value>
		</wp:postmeta>
		{foreach from=$aItem.comment item=comment}
								<wp:comment>
		<wp:comment_id>{$comment.comment_id}</wp:comment_id>
		<wp:comment_author><![CDATA[{$comment.user_name}]]></wp:comment_author>
		<wp:comment_author_email>{$comment.email}</wp:comment_author_email>
		<wp:comment_author_url>http://{$comment.user_name}.wordpress.com</wp:comment_author_url>
		<wp:comment_author_IP></wp:comment_author_IP>
		<wp:comment_date>2011-04-26 07:34:16</wp:comment_date>
		<wp:comment_date_gmt>2011-04-26 07:34:16</wp:comment_date_gmt>
		<wp:comment_content><![CDATA[{$comment.text}]]></wp:comment_content>
		<wp:comment_approved>0</wp:comment_approved>
		<wp:comment_type></wp:comment_type>
		<wp:comment_parent>0</wp:comment_parent>
		<wp:comment_user_id>{$comment.owner_user_id}</wp:comment_user_id>
		</wp:comment>
		{/foreach}
			</item>
	{/foreach}
	</channel>
</rss>
