<upgrade>
	<phpfox_update_settings>
		<setting>
			<group />
			<module_id>comment</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>wysiwyg_comments</var_name>
			<phrase_var_name>setting_wysiwyg_comments</phrase_var_name>
			<ordering>0</ordering>
			<version_id>2.0.0alpha1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group />
			<module_id>comment</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>comment_is_threaded</var_name>
			<phrase_var_name>setting_comment_is_threaded</phrase_var_name>
			<ordering>1</ordering>
			<version_id>2.0.0alpha1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group />
			<module_id>comment</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>allow_rss_feed_on_comments</var_name>
			<phrase_var_name>setting_allow_rss_feed_on_comments</phrase_var_name>
			<ordering>1</ordering>
			<version_id>2.0.0beta5</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group />
			<module_id>comment</module_id>
			<is_hidden>1</is_hidden>
			<type>integer</type>
			<var_name>total_child_comments</var_name>
			<phrase_var_name>setting_total_child_comments</phrase_var_name>
			<ordering>1</ordering>
			<version_id>2.0.0rc1</version_id>
			<value>4</value>
		</setting>
		<setting>
			<group />
			<module_id>comment</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>allow_comments_on_profiles</var_name>
			<phrase_var_name>setting_allow_comments_on_profiles</phrase_var_name>
			<ordering>1</ordering>
			<version_id>2.0.0rc4</version_id>
			<value>1</value>
		</setting>
	</phpfox_update_settings>
</upgrade>