<upgrade>
	<phrases>
		<phrase>
			<module_id>input</module_id>
			<version_id>3.5.0beta2</version_id>
			<var_name>add_input_field</var_name>
			<added>1359469512</added>
			<value>Add Input Field</value>
		</phrase>
		<phrase>
			<module_id>input</module_id>
			<version_id>3.5.0beta2</version_id>
			<var_name>yes</var_name>
			<added>1359469607</added>
			<value>Yes</value>
		</phrase>
		<phrase>
			<module_id>input</module_id>
			<version_id>3.5.0beta2</version_id>
			<var_name>no</var_name>
			<added>1359469614</added>
			<value>No</value>
		</phrase>
	</phrases>
</upgrade>