<upgrade>
	<phrases>
		<phrase>
			<module_id>group</module_id>
			<version_id>2.0.6</version_id>
			<var_name>member</var_name>
			<added>1283941479</added>
			<value>Member</value>
		</phrase>
		<phrase>
			<module_id>group</module_id>
			<version_id>2.0.6</version_id>
			<var_name>invited</var_name>
			<added>1283941496</added>
			<value>Invited</value>
		</phrase>
	</phrases>
	<update_templates>
		<file type="controller">view.html.php</file>
	</update_templates>
</upgrade>