<upgrade>
	<phrases>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.4.0</version_id>
			<var_name>likes</var_name>
			<added>1351494364</added>
			<value>Likes</value>
		</phrase>
	</phrases>
</upgrade>