<upgrade>
	<phrases>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.5.0</version_id>
			<var_name>like_uppercase</var_name>
			<added>1361783897</added>
			<value>Like</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.5.0</version_id>
			<var_name>unlike_uppercase</var_name>
			<added>1361783926</added>
			<value>Unlike</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.5.0</version_id>
			<var_name>dislike</var_name>
			<added>1361783942</added>
			<value>Dislike</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.5.0</version_id>
			<var_name>undislike</var_name>
			<added>1361783968</added>
			<value>Undislike</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.5.0</version_id>
			<var_name>remove</var_name>
			<added>1361801562</added>
			<value>Remove</value>
		</phrase>
	</phrases>
</upgrade>