<upgrade>
  <phrases>
    <phrase>
      <module_id>like</module_id>
      <version_id>4.0.10</version_id>
      <var_name>liked</var_name>
      <added>1444797045</added>
      <value>Liked</value>
    </phrase>
  </phrases>
</upgrade>