<upgrade>
	<settings>
		<setting>
			<group>cache</group>
			<module_id>friend</module_id>
			<is_hidden>0</is_hidden>
			<type>integer</type>
			<var_name>cache_mutual_friends</var_name>
			<phrase_var_name>setting_cache_mutual_friends</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>friend</module_id>
			<is_hidden>0</is_hidden>
			<type>integer</type>
			<var_name>cache_rand_list_of_friends</var_name>
			<phrase_var_name>setting_cache_rand_list_of_friends</phrase_var_name>
			<ordering>3</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>60</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>friend</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>cache_is_friend</var_name>
			<phrase_var_name>setting_cache_is_friend</phrase_var_name>
			<ordering>4</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>friend</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>cache_friend_list</var_name>
			<phrase_var_name>setting_cache_friend_list</phrase_var_name>
			<ordering>5</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>friend</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>load_friends_online_ajax</var_name>
			<phrase_var_name>setting_load_friends_online_ajax</phrase_var_name>
			<ordering>6</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
	</settings>
	<phrases>
		<phrase>
			<module_id>friend</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_cache_mutual_friends</var_name>
			<added>1371724056</added>
			<value><![CDATA[<title>Mutual Friends List</title><info>Minutes, 0 = no cache. Caches the list of mutual friends with specific users.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>friend</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_cache_rand_list_of_friends</var_name>
			<added>1371724112</added>
			<value><![CDATA[<title>Friends List</title><info>Minutes. 0 = no cache. Block is friend.small in the profiles, defaults to the left column. It is also called from the timeline block in the friend module.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>friend</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_cache_is_friend</var_name>
			<added>1371724166</added>
			<value><![CDATA[<title>Friends Check</title><info>Cache if a user is friends with another user. Cleared only when adding or removing a friend.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>friend</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_cache_friend_list</var_name>
			<added>1371724202</added>
			<value><![CDATA[<title>Friends List (FULL)</title><info>Cache the users friends list so we don&#039;t query the database all the time.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>friend</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_load_friends_online_ajax</var_name>
			<added>1371731879</added>
			<value><![CDATA[<title>Online Friends via AJAX</title><info>Load the Online Friends only after the site has loaded via AJAX.</info>]]></value>
		</phrase>
	</phrases>
</upgrade>