<upgrade>
	<phrases>
		<phrase>
			<module_id>user</module_id>
			<version_id>3.1.0</version_id>
			<var_name>to</var_name>
			<added>1332764521</added>
			<value>to</value>
		</phrase>
		<phrase>
			<module_id>user</module_id>
			<version_id>3.1.0</version_id>
			<var_name>with</var_name>
			<added>1332765004</added>
			<value>with</value>
		</phrase>
	</phrases>
</upgrade>