<upgrade>
	<phrases>
		<phrase>
			<module_id>comment</module_id>
			<version_id>3.1.0rc1</version_id>
			<var_name>user_setting_can_delete_comment_on_own_item</var_name>
			<added>1332248539</added>
			<value>Can delete any comments posted on their own item?</value>
		</phrase>
		<phrase>
			<module_id>comment</module_id>
			<version_id>3.2.0beta1</version_id>
			<var_name>comment_on_items</var_name>
			<added>1334578769</added>
			<value>Comment on Items</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>comment</module_id>
			<type>boolean</type>
			<admin>0</admin>
			<user>0</user>
			<guest>0</guest>
			<staff>0</staff>
			<module>comment</module>
			<ordering>0</ordering>
			<value>can_delete_comment_on_own_item</value>
		</setting>
	</user_group_settings>
</upgrade>