<upgrade>
	<settings>
		<setting>
			<group>cache</group>
			<module_id>comment</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>load_delayed_comments_items</var_name>
			<phrase_var_name>setting_load_delayed_comments_items</phrase_var_name>
			<ordering>1</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
	</settings>
	<phrases>
		<phrase>
			<module_id>comment</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_load_delayed_comments_items</var_name>
			<added>1371732573</added>
			<value><![CDATA[<title>Load Comments via AJAX</title><info>Enable to load comments via AJAX when viewing items.</info>]]></value>
		</phrase>
	</phrases>
</upgrade>