<upgrade>
	<phrases>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.3.0beta2</version_id>
			<var_name>sponsored</var_name>
			<added>1340791705</added>
			<value>Sponsored</value>
		</phrase>
	</phrases>
</upgrade>