<upgrade>
	<phrases>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.5.1</version_id>
			<var_name>dimensions</var_name>
			<added>1366792170</added>
			<value>Dimensions</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.5.1</version_id>
			<var_name>ad_dimensions_are_in_pixels</var_name>
			<added>1366792177</added>
			<value>Ad dimensions are in pixels.</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.5.1</version_id>
			<var_name>width</var_name>
			<added>1366792186</added>
			<value>Width</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.5.1</version_id>
			<var_name>height</var_name>
			<added>1366792192</added>
			<value>Height</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.5.1</version_id>
			<var_name>placement_type</var_name>
			<added>1366792202</added>
			<value>Placement Type</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.5.1</version_id>
			<var_name>cpm_cost_per_mille</var_name>
			<added>1366792209</added>
			<value>CPM (Cost per mille)</value>
		</phrase>
		<phrase>
			<module_id>ad</module_id>
			<version_id>3.5.1</version_id>
			<var_name>ppc_pay_per_click</var_name>
			<added>1366792217</added>
			<value>PPC (Pay per click)</value>
		</phrase>
	</phrases>
</upgrade>