<upgrade>
	<phrases>
		<phrase>
			<module_id>theme</module_id>
			<version_id>3.5.0</version_id>
			<var_name>favorites</var_name>
			<added>1361783592</added>
			<value>Favorites</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>3.5.0</version_id>
			<var_name>edit</var_name>
			<added>1361783599</added>
			<value>Edit</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>3.5.0</version_id>
			<var_name>edit_profile</var_name>
			<added>1361783606</added>
			<value>Edit Profile</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>3.5.0</version_id>
			<var_name>view_more</var_name>
			<added>1361783682</added>
			<value>View More</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>3.5.0</version_id>
			<var_name>view_less</var_name>
			<added>1361783688</added>
			<value>View Less</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>3.5.0</version_id>
			<var_name>add_more</var_name>
			<added>1361783694</added>
			<value>Add More</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>3.5.0</version_id>
			<var_name>done</var_name>
			<added>1361783708</added>
			<value>Done</value>
		</phrase>
	</phrases>
	<hooks>
		<hook>
			<module_id>theme</module_id>
			<hook_type>service</hook_type>
			<module>theme</module>
			<call_name>theme.service_style_getstyles__1</call_name>
			<added>1363075699</added>
			<version_id>3.5.0</version_id>
			<value />
		</hook>
	</hooks>
</upgrade>