<upgrade>
	<phrases>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>you</var_name>
			<added>1319121089</added>
			<value>You</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>you_and</var_name>
			<added>1319121111</added>
			<value>You and</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>you_comma</var_name>
			<added>1319121128</added>
			<value>You,</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>and</var_name>
			<added>1319121140</added>
			<value>and</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>1_other_person</var_name>
			<added>1319121152</added>
			<value>1 other person</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>others</var_name>
			<added>1319121160</added>
			<value>others</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>like_this</var_name>
			<added>1319121169</added>
			<value>like this.</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>likes_this</var_name>
			<added>1319121177</added>
			<value>likes this.</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>1_person</var_name>
			<added>1319121390</added>
			<value>1 person</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>total_people</var_name>
			<added>1319121408</added>
			<value>{total} people</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>members</var_name>
			<added>1319122349</added>
			<value>Members</value>
		</phrase>
		<phrase>
			<module_id>like</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>people_who_like_this</var_name>
			<added>1319122357</added>
			<value>People who like this</value>
		</phrase>
	</phrases>
</upgrade>