<upgrade>
	<phrases>
		<phrase>
			<module_id>pages</module_id>
			<version_id>3.5.1</version_id>
			<var_name>location</var_name>
			<added>1366783890</added>
			<value>Location</value>
		</phrase>
	</phrases>
</upgrade>