<upgrade>
	<phrases>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>categories</var_name>
			<added>1253022948</added>
			<value>Categories</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>fill_in_some_text_for_your_message</var_name>
			<added>1253022992</added>
			<value>Fill in some text for your message.</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>you_need_to_choose_a_category</var_name>
			<added>1253023004</added>
			<value>You need to choose a category.</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>provide_a_subject</var_name>
			<added>1253023017</added>
			<value>Provide a subject.</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>provide_your_full_name</var_name>
			<added>1253023027</added>
			<value>Provide your full name.</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>provide_a_valid_email</var_name>
			<added>1253023050</added>
			<value>Provide a valid email.</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>your_message_was_successfully_sent</var_name>
			<added>1253023065</added>
			<value>Your message was successfully sent.</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>contact_us</var_name>
			<added>1253082677</added>
			<value>Contact Us</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>add_a_new_category</var_name>
			<added>1253082767</added>
			<value>Add a New Category</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>category</var_name>
			<added>1253082775</added>
			<value>Category</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>add</var_name>
			<added>1253082784</added>
			<value>Add</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>manage_categories</var_name>
			<added>1253082798</added>
			<value>Manage Categories</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>order</var_name>
			<added>1253082808</added>
			<value>Order</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>select</var_name>
			<added>1253082841</added>
			<value>Select</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>full_name</var_name>
			<added>1253082855</added>
			<value>Full Name</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>subject</var_name>
			<added>1253082865</added>
			<value>Subject</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>email</var_name>
			<added>1253082875</added>
			<value>Email</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>website</var_name>
			<added>1253082883</added>
			<value>Website</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>message</var_name>
			<added>1253083188</added>
			<value>Message</value>
		</phrase>
		<phrase>
			<module_id>contact</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>submit</var_name>
			<added>1253083201</added>
			<value>Submit</value>
		</phrase>
	</phrases>
</upgrade>