<upgrade>
	<settings>
		<setting>
			<group>embedly</group>
			<module_id>video</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>enabled_embedly_import</var_name>
			<phrase_var_name>setting_enabled_embedly_import</phrase_var_name>
			<ordering>1</ordering>
			<version_id>3.0.1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group>embedly</group>
			<module_id>video</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>embedly_api_key</var_name>
			<phrase_var_name>setting_embedly_api_key</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.0.1</version_id>
			<value />
		</setting>
	</settings>
	<setting_groups>
		<name>
			<module_id>video</module_id>
			<version_id>3.0.1</version_id>
			<var_name>setting_group_embedly</var_name>
			<value>embedly</value>
		</name>
	</setting_groups>
	<phrases>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.1</version_id>
			<var_name>setting_group_embedly</var_name>
			<added>1327498650</added>
			<value><![CDATA[<title>Embed.ly</title><info>Embedly provides a powerful API to convert standard URLs into embedded videos and images.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.1</version_id>
			<var_name>setting_enabled_embedly_import</var_name>
			<added>1327499697</added>
			<value><![CDATA[<title>Enable Embed.ly Support</title><info><a href="http://embed.ly/" target="_blank">Embedly</a> provides a powerful API to convert standard URLs into embedded videos, images, and rich article previews from 218 leading providers.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.1</version_id>
			<var_name>setting_embedly_api_key</var_name>
			<added>1327500393</added>
			<value><![CDATA[<title>Embed.ly API Key</title><info>Enter your API key here.</info>]]></value>
		</phrase>
	</phrases>
</upgrade>