<upgrade>
	<phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>name</var_name>
			<added>1294829089</added>
			<value>Name</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>in_queue</var_name>
			<added>1294829175</added>
			<value>In queue</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>more_queued_than_allowed</var_name>
			<added>1296557912</added>
			<value>Please only select {iQueueLimit} files</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>stopped</var_name>
			<added>1297081376</added>
			<value>Stopped</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>manage_activity_points</var_name>
			<added>1297418856</added>
			<value>Manage Activity Points</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>multiple_selection</var_name>
			<added>1297678709</added>
			<value>Multiple Selection</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>radio</var_name>
			<added>1297688811</added>
			<value>Radio</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.8</version_id>
			<var_name>checkbox</var_name>
			<added>1297690696</added>
			<value>Checkbox</value>
		</phrase>
	</phrases>
</upgrade>