<upgrade>
	<phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>welcome_email_content</var_name>
			<added>1256828212</added>
			<value>Thanks for joining our community!</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>welcome_email_subject</var_name>
			<added>1256828898</added>
			<value><![CDATA[Welcome to {setting var='core.site_title'}]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>monday</var_name>
			<added>1256832175</added>
			<value>Monday</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>tuesday</var_name>
			<added>1256832914</added>
			<value>Tuesday</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>wednesday</var_name>
			<added>1256832954</added>
			<value>Wednesday</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>thursday</var_name>
			<added>1256832979</added>
			<value>Thursday</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>friday</var_name>
			<added>1256833008</added>
			<value>Friday</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>saturday</var_name>
			<added>1256833052</added>
			<value>Saturday</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc5</version_id>
			<var_name>sunday</var_name>
			<added>1256833073</added>
			<value>Sunday</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.0.0rc6</version_id>
			<var_name>view_less</var_name>
			<added>1257261878</added>
			<value>View Less</value>
		</phrase>
	</phrases>
	<update_templates>
		<file type="block">note.html.php</file>
		<file type="block">footer.html.php</file>
		<file type="layout">error.html.php</file>
	</update_templates>
	<update_styles>
		<file type="layout">layout.css</file>
	</update_styles>
</upgrade>