<upgrade>
	<phrases>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>edit_profile</var_name>
			<added>1319115269</added>
			<value>Edit Profile</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>design_profile</var_name>
			<added>1319115276</added>
			<value>Design Profile</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>send_message</var_name>
			<added>1319115286</added>
			<value>Send Message</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>confirm_friend_request</var_name>
			<added>1319115297</added>
			<value>Confirm Friend Request</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>more</var_name>
			<added>1319115311</added>
			<value>More</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>edit_friends</var_name>
			<added>1319115320</added>
			<value>Edit Friends</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>pending_friend_confirmation</var_name>
			<added>1319115341</added>
			<value>Pending Friend Confirmation</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>pending_friend_request</var_name>
			<added>1319115347</added>
			<value>Pending Friend Request</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>lives_in</var_name>
			<added>1319115363</added>
			<value>Lives in</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>age_years_old</var_name>
			<added>1319115376</added>
			<value>{age} years old</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>born_on_birthday</var_name>
			<added>1319115394</added>
			<value>Born on {birthday}</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>relationship_status</var_name>
			<added>1319115416</added>
			<value>Relationship status</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>message</var_name>
			<added>1319115456</added>
			<value>Message</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>change_picture</var_name>
			<added>1319115749</added>
			<value>Change Picture</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>drafts</var_name>
			<added>1319116115</added>
			<value>Drafts</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>blogs</var_name>
			<added>1319116123</added>
			<value>Blogs</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>polls</var_name>
			<added>1319116135</added>
			<value>Polls</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>friends</var_name>
			<added>1319116148</added>
			<value>Friends</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>videos</var_name>
			<added>1319116160</added>
			<value>Videos</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>events</var_name>
			<added>1319116169</added>
			<value>Events</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>guestbook</var_name>
			<added>1319116179</added>
			<value>Guestbook</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>listings</var_name>
			<added>1319116189</added>
			<value>Listings</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>music</var_name>
			<added>1319116201</added>
			<value>Music</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>albums</var_name>
			<added>1319116213</added>
			<value>Albums</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>photos</var_name>
			<added>1319116219</added>
			<value>Photos</value>
		</phrase>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>quizzes</var_name>
			<added>1319116230</added>
			<value>Quizzes</value>
		</phrase>
	</phrases>
</upgrade>