<upgrade>
	<phrases>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>viewing_video</var_name>
			<added>1319121862</added>
			<value>Viewing Video</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>title</var_name>
			<added>1319122758</added>
			<value>Title</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>select_a_video_to_attach</var_name>
			<added>1319122771</added>
			<value>Select a video to attach.</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>video_has_been_approved</var_name>
			<added>1319183708</added>
			<value>Video has been approved.</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>video_approved</var_name>
			<added>1319183716</added>
			<value>Video Approved</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>go_advanced_uppercase</var_name>
			<added>1319198040</added>
			<value>Go Advanced</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>cancel_uppercase</var_name>
			<added>1319198053</added>
			<value>Cancel</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>search_videos</var_name>
			<added>1319198077</added>
			<value>Search Videos...</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>latest</var_name>
			<added>1319198083</added>
			<value>Latest</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>most_liked</var_name>
			<added>1319198098</added>
			<value>Most Liked</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>all_videos</var_name>
			<added>1319198120</added>
			<value>All Videos</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>my_videos</var_name>
			<added>1319198127</added>
			<value>My Videos</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>friends_videos</var_name>
			<added>1319198136</added>
			<value><![CDATA[Friends' Videos]]></value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>featured_videos</var_name>
			<added>1319198144</added>
			<value>Featured Videos</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>topic</var_name>
			<added>1319198185</added>
			<value>Topic</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>approve</var_name>
			<added>1319198200</added>
			<value>Approve</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>your_video_has_successfully_been_uploaded_please_standby_while_we_convert_your_video</var_name>
			<added>1319198239</added>
			<value>Your video has successfully been uploaded. Please standby while we convert your video.</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>upload_problems_try_the_basic_uploader</var_name>
			<added>1319198271</added>
			<value><![CDATA[Upload problems? Try the <a href="{link}">basic uploader</a> (works on older computers and web browsers).]]></value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>upload</var_name>
			<added>1319198287</added>
			<value>Upload</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>click_here_to_view_a_list_of_supported_sites</var_name>
			<added>1319198319</added>
			<value><![CDATA[Click <a href="#" onclick="$Core.box('video.supportedSites', 600); return false;">here</a> to view a list of supported sites you can import videos from.]]></value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>privacy</var_name>
			<added>1319198327</added>
			<value>Privacy</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>control_who_can_see_this_video</var_name>
			<added>1319198336</added>
			<value>Control who can see this video.</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>comment_privacy</var_name>
			<added>1319198343</added>
			<value>Comment Privacy</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>control_who_can_comment_on_this_video</var_name>
			<added>1319198352</added>
			<value>Control who can comment on this video.</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>link</var_name>
			<added>1319198605</added>
			<value>Link</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>un_sponsor</var_name>
			<added>1319198617</added>
			<value>Un-Sponsor</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>sponsor</var_name>
			<added>1319198623</added>
			<value>Sponsor</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>feature</var_name>
			<added>1319198632</added>
			<value>Feature</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>un_feature</var_name>
			<added>1319198641</added>
			<value>Un-Feature</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>sponsored</var_name>
			<added>1319198652</added>
			<value>Sponsored</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>moderate</var_name>
			<added>1319198660</added>
			<value>Moderate</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>by_full_name</var_name>
			<added>1319198682</added>
			<value>by {full_name}</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>actions</var_name>
			<added>1319198997</added>
			<value>Actions</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>show_more</var_name>
			<added>1319199102</added>
			<value>Show More</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>show_less</var_name>
			<added>1319199109</added>
			<value>Show Less</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>report_this_video</var_name>
			<added>1319199203</added>
			<value>Report this video</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>unable_to_view_this_item_due_to_privacy_settings</var_name>
			<added>1319199213</added>
			<value>Unable to view this item due to privacy settings.</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>editing_video</var_name>
			<added>1319199289</added>
			<value>Editing Video</value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>full_name_liked_your_video_title</var_name>
			<added>1319530124</added>
			<value><![CDATA[{full_name} liked your video "{title}"]]></value>
		</phrase>
		<phrase>
			<module_id>video</module_id>
			<version_id>3.0.0beta5</version_id>
			<var_name>full_name_liked_your_video_message</var_name>
			<added>1319530311</added>
			<value><![CDATA[{full_name} liked your video "<a href="{link}">{title}</a>"
To view this video follow the link below:
<a href="{link}">{link}</a>]]></value>
		</phrase>
	</phrases>
</upgrade>