<upgrade>
	<phrases>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>filter_successfully_deleted</var_name>
			<added>1252926663</added>
			<value>Filter successfully deleted.</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>filter_successfully_added</var_name>
			<added>1252926676</added>
			<value>Filter successfully added.</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ban</var_name>
			<added>1252926684</added>
			<value>Ban</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>display_names</var_name>
			<added>1252926710</added>
			<value>Display Names</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>display_name</var_name>
			<added>1252926721</added>
			<value>Display Name</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>emails</var_name>
			<added>1252926731</added>
			<value>Emails</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>email</var_name>
			<added>1252926738</added>
			<value>Email</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ip_addresses</var_name>
			<added>1252926751</added>
			<value>IP Addresses</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>ip_address</var_name>
			<added>1252926760</added>
			<value>IP Address</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>usernames</var_name>
			<added>1252926770</added>
			<value>Usernames</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>username</var_name>
			<added>1252926777</added>
			<value>Username</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>words</var_name>
			<added>1252926787</added>
			<value>Words</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>word</var_name>
			<added>1252926794</added>
			<value>Word</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>filter_value_is_required</var_name>
			<added>1252926832</added>
			<value>Filter value is required.</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>filter_replacement_is_required</var_name>
			<added>1252926846</added>
			<value>Filter replacement is required.</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>add_filter</var_name>
			<added>1252926887</added>
			<value>Add Filter</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>use_the_asterisk_for_wildcard_entries</var_name>
			<added>1252926938</added>
			<value><![CDATA[Use the asterisk (&#42;) for wildcard entries.]]></value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>replacement</var_name>
			<added>1252926946</added>
			<value>Replacement</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>add</var_name>
			<added>1252926955</added>
			<value>Add</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>added_by</var_name>
			<added>1252926974</added>
			<value>Added By</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>added_on</var_name>
			<added>1252926982</added>
			<value>Added On</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>delete</var_name>
			<added>1252926996</added>
			<value>Delete</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>are_you_sure</var_name>
			<added>1252927003</added>
			<value>Are you sure?</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>n_a</var_name>
			<added>1252927037</added>
			<value>N/A</value>
		</phrase>
		<phrase>
			<module_id>ban</module_id>
			<version_id>2.0.0rc2</version_id>
			<var_name>you_have_been_banned_for_spamming</var_name>
			<added>1252927064</added>
			<value>You have been banned for spamming.</value>
		</phrase>
	</phrases>
</upgrade>