<upgrade>
	<phrases>
		<phrase>
			<module_id>poll</module_id>
			<version_id>2.0.0rc11</version_id>
			<var_name>user_setting_can_access_polls</var_name>
			<added>1260276844</added>
			<value>Can browse and view polls?</value>
		</phrase>
		<phrase>
			<module_id>poll</module_id>
			<version_id>2.0.0rc11</version_id>
			<var_name>user_setting_can_create_poll</var_name>
			<added>1260329272</added>
			<value>Can create a poll?</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>poll</module_id>
			<type>boolean</type>
			<admin>1</admin>
			<user>1</user>
			<guest>1</guest>
			<staff>1</staff>
			<module>poll</module>
			<ordering>0</ordering>
			<value>can_access_polls</value>
		</setting>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>poll</module_id>
			<type>boolean</type>
			<admin>1</admin>
			<user>1</user>
			<guest>0</guest>
			<staff>1</staff>
			<module>poll</module>
			<ordering>0</ordering>
			<value>can_create_poll</value>
		</setting>
	</user_group_settings>
</upgrade>