<upgrade>
	<phrases>
		<phrase>
			<module_id>invite</module_id>
			<version_id>2.0.0rc8</version_id>
			<var_name>invites</var_name>
			<added>1258500553</added>
			<value>Invites</value>
		</phrase>
	</phrases>
</upgrade>