<upgrade>
	<phrases>
		<phrase>
			<module_id>feed</module_id>
			<version_id>3.7.0beta1</version_id>
			<var_name>user_setting_can_purchase_sponsor</var_name>
			<added>1375264862</added>
			<value>Can members of this user group sponsor feeds?</value>
		</phrase>
	</phrases>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>boolean</type>
			<admin>false</admin>
			<user>false</user>
			<guest>false</guest>
			<staff>false</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>can_purchase_sponsor</value>
		</setting>
	</user_group_settings>
</upgrade>