<upgrade>
	<phrases>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>last_modified_time_stamp_by_full_name</var_name>
			<added>1255341569</added>
			<value>Last modified {time_stamp} by {full_name}</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>css_file_successfully_added</var_name>
			<added>1255341673</added>
			<value>CSS file successfully added.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>not_a_valid_style</var_name>
			<added>1255341684</added>
			<value>Not a valid style.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>edit_css</var_name>
			<added>1255341692</added>
			<value>Edit CSS</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>themes</var_name>
			<added>1255341702</added>
			<value>Themes</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>styles</var_name>
			<added>1255341707</added>
			<value>Styles</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>editing_style</var_name>
			<added>1255341724</added>
			<value>Editing Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>create_new_style</var_name>
			<added>1255341735</added>
			<value>Create New Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style_successfully_updated</var_name>
			<added>1255342251</added>
			<value>Style successfully updated.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style_successfully_added</var_name>
			<added>1255342260</added>
			<value>Style successfully added.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>create_style</var_name>
			<added>1255342279</added>
			<value>Create Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>import_styles</var_name>
			<added>1255342298</added>
			<value>Import Styles</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style_successfully_imported</var_name>
			<added>1255342393</added>
			<value>Style successfully imported.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>not_a_valid_theme</var_name>
			<added>1255342410</added>
			<value>Not a valid theme.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style_successfully_deleted</var_name>
			<added>1255342418</added>
			<value>Style successfully deleted.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>managing_styles_for</var_name>
			<added>1255342425</added>
			<value>Managing styles for</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>logo_successfully_reverted</var_name>
			<added>1255342457</added>
			<value>Logo successfully reverted.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>logo_successfully_uploaded</var_name>
			<added>1255342467</added>
			<value>Logo successfully uploaded.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>change_site_logo</var_name>
			<added>1255342474</added>
			<value>Change Site Logo</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>change_logo</var_name>
			<added>1255342493</added>
			<value>Change Logo</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>template_successfully_added</var_name>
			<added>1255342506</added>
			<value>Template successfully added.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>create_new_template</var_name>
			<added>1255342536</added>
			<value>Create New Template</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>templates</var_name>
			<added>1255342553</added>
			<value>Templates</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_successfully_updated</var_name>
			<added>1255342573</added>
			<value>Theme successfully updated.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_successfully_added</var_name>
			<added>1255342583</added>
			<value>Theme successfully added.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>editing_theme</var_name>
			<added>1255342590</added>
			<value>Editing Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>create_new_theme</var_name>
			<added>1255342598</added>
			<value>Create New Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>create_theme</var_name>
			<added>1255342624</added>
			<value>Create Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_is_not_valid</var_name>
			<added>1255342635</added>
			<value>Theme is not valid.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>export_theme</var_name>
			<added>1255342643</added>
			<value>Export Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_successfully_imported</var_name>
			<added>1255342668</added>
			<value>Theme successfully imported.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>not_a_valid_theme_to_import</var_name>
			<added>1255342677</added>
			<value>Not a valid theme to import.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>import_themes</var_name>
			<added>1255342684</added>
			<value>Import Themes</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_successfully_deleted</var_name>
			<added>1255342706</added>
			<value>Theme successfully deleted.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>not_a_valid_file_extension</var_name>
			<added>1255342775</added>
			<value>Not a valid file extension.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>unable_to_upload_image</var_name>
			<added>1255342800</added>
			<value>Unable to upload image.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>unable_to_find_style</var_name>
			<added>1255342813</added>
			<value>Unable to find style.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style_requires_a_name</var_name>
			<added>1255342829</added>
			<value>Style requires a name.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style_requires_a_folder_name</var_name>
			<added>1255342836</added>
			<value>Style requires a folder name.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>select_a_parent_theme_for_this_style</var_name>
			<added>1255342843</added>
			<value>Select a parent theme for this style.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>provide_if_the_style_is_active_or_not</var_name>
			<added>1255342850</added>
			<value>Provide if the style is active or not.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>provide_a_default_logo_name</var_name>
			<added>1255342858</added>
			<value>Provide a default logo name.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>folder_is_not_valid</var_name>
			<added>1255342866</added>
			<value>Folder is not valid.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>this_folder_is_already_in_use</var_name>
			<added>1255342874</added>
			<value><![CDATA[This "Folder" is already in use.]]></value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>select_a_style</var_name>
			<added>1255342895</added>
			<value>Select a style.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>provide_a_file_name</var_name>
			<added>1255342901</added>
			<value>Provide a file name.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>provide_css_code</var_name>
			<added>1255342915</added>
			<value>Provide CSS code.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>file_name_is_not_valid</var_name>
			<added>1255342923</added>
			<value>File name is not valid.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>the_file_name_is_already_in_use</var_name>
			<added>1255342931</added>
			<value><![CDATA[The "File Name" is already in use.]]></value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>not_a_valid_style_to_set_to_default</var_name>
			<added>1255342990</added>
			<value>Not a valid style to set to default.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>unable_to_find_style_sheet</var_name>
			<added>1255343035</added>
			<value>Unable to find style sheet.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>unable_to_find_the_style_sheet_file</var_name>
			<added>1255343045</added>
			<value>Unable to find the style sheet file.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>select_a_theme_for_this_template</var_name>
			<added>1255343095</added>
			<value>Select a theme for this template.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>select_what_type_of_a_template_this_is</var_name>
			<added>1255343103</added>
			<value>Select what type of a template this is.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>not_a_valid_template_to_delete</var_name>
			<added>1255343159</added>
			<value>Not a valid template to delete.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_requires_a_name</var_name>
			<added>1255343189</added>
			<value>Theme requires a name.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_requires_a_folder_name</var_name>
			<added>1255343196</added>
			<value>Theme requires a folder name.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>provide_if_the_theme_is_active_or_not</var_name>
			<added>1255343205</added>
			<value>Provide if the theme is active or not.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>there_is_already_a_theme_with_the_same_folder_name</var_name>
			<added>1255343286</added>
			<value>There is already a theme with the same folder name.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>not_a_valid_theme_to_delete</var_name>
			<added>1255343324</added>
			<value>Not a valid theme to delete.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>full_screen</var_name>
			<added>1255343483</added>
			<value>Full Screen</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>toggle</var_name>
			<added>1255343492</added>
			<value>Toggle</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>blocks</var_name>
			<added>1255343499</added>
			<value>Blocks</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>toggle_all_blocks</var_name>
			<added>1255343507</added>
			<value>Toggle all blocks.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>close</var_name>
			<added>1255343514</added>
			<value>Close</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>advanced</var_name>
			<added>1255343533</added>
			<value>Advanced</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>css</var_name>
			<added>1255343540</added>
			<value>CSS</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>use_theme</var_name>
			<added>1255343554</added>
			<value>Use Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>save</var_name>
			<added>1255343567</added>
			<value>Save</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>preview</var_name>
			<added>1255343573</added>
			<value>Preview</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>revert_to_default</var_name>
			<added>1255343591</added>
			<value>Revert To Default</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>are_you_sure_note_that_this_will_revert_all_your_changes_and_not_just_those_within_this_group</var_name>
			<added>1255343603</added>
			<value>Are you sure? Note that this will revert all your changes and not just those within this group.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>width</var_name>
			<added>1255343620</added>
			<value>Width</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>default</var_name>
			<added>1255343632</added>
			<value><![CDATA[[Default]]]></value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>background</var_name>
			<added>1255343644</added>
			<value>Background</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>url</var_name>
			<added>1255343670</added>
			<value>URL</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>attach_files</var_name>
			<added>1255343681</added>
			<value>Attach Files</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>scroll</var_name>
			<added>1255343687</added>
			<value>Scroll</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>yes</var_name>
			<added>1255343701</added>
			<value>Yes</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>no</var_name>
			<added>1255343707</added>
			<value>No</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>position</var_name>
			<added>1255343718</added>
			<value>Position</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>repeat</var_name>
			<added>1255343727</added>
			<value>Repeat</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>do_not_repeat</var_name>
			<added>1255343737</added>
			<value>Do Not Repeat</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>across</var_name>
			<added>1255343743</added>
			<value>Across</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>down</var_name>
			<added>1255343749</added>
			<value>Down</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>tile</var_name>
			<added>1255343755</added>
			<value>Tile</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>font</var_name>
			<added>1255343762</added>
			<value>Font</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>color</var_name>
			<added>1255343769</added>
			<value>Color</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>family</var_name>
			<added>1255343779</added>
			<value>Family</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>size</var_name>
			<added>1255343801</added>
			<value>Size</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style</var_name>
			<added>1255343816</added>
			<value>Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>weight</var_name>
			<added>1255343826</added>
			<value>Weight</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>text</var_name>
			<added>1255343834</added>
			<value>Text</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>align</var_name>
			<added>1255343840</added>
			<value>Align</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>transform</var_name>
			<added>1255343851</added>
			<value>Transform</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>decoration</var_name>
			<added>1255343860</added>
			<value>Decoration</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>border</var_name>
			<added>1255343872</added>
			<value>Border</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>padding</var_name>
			<added>1255343939</added>
			<value>Padding</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>reset</var_name>
			<added>1255343959</added>
			<value>Reset</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>css_details</var_name>
			<added>1255344281</added>
			<value>CSS Details</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>select</var_name>
			<added>1255344295</added>
			<value>Select</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>file_name</var_name>
			<added>1255344302</added>
			<value>File Name</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>creator</var_name>
			<added>1255344309</added>
			<value>Creator</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>submit</var_name>
			<added>1255344322</added>
			<value>Submit</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>css_files</var_name>
			<added>1255344333</added>
			<value>CSS Files</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>global_css</var_name>
			<added>1255344341</added>
			<value>Global CSS</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>revert</var_name>
			<added>1255344362</added>
			<value>Revert</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>delete</var_name>
			<added>1255344368</added>
			<value>Delete</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>style_details</var_name>
			<added>1255344380</added>
			<value>Style Details</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>parent_theme</var_name>
			<added>1255344387</added>
			<value>Parent Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>parent_style</var_name>
			<added>1255344399</added>
			<value>Parent Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>name</var_name>
			<added>1255344406</added>
			<value>Name</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>folder_name</var_name>
			<added>1255344413</added>
			<value>Folder Name</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>logo_image</var_name>
			<added>1255344420</added>
			<value>Logo Image</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>default_logo_file_name_eg_logo_png</var_name>
			<added>1255344427</added>
			<value>Default logo file name (eg. logo.png)</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>website</var_name>
			<added>1255344440</added>
			<value>Website</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>version</var_name>
			<added>1255344447</added>
			<value>Version</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>is_default</var_name>
			<added>1255344455</added>
			<value>Is Default</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>is_active</var_name>
			<added>1255344489</added>
			<value>Is Active</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>update</var_name>
			<added>1255344510</added>
			<value>Update</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>manual_install</var_name>
			<added>1255344530</added>
			<value>Manual Install</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme</var_name>
			<added>1255344536</added>
			<value>Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>created_by</var_name>
			<added>1255344548</added>
			<value>Created By</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>action</var_name>
			<added>1255344559</added>
			<value>Action</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>n_a</var_name>
			<added>1255344568</added>
			<value>N/A</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>install</var_name>
			<added>1255344589</added>
			<value>Install</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>click_to_install_this_theme</var_name>
			<added>1255344596</added>
			<value>Click to install this theme.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>nothing_new_to_install</var_name>
			<added>1255344602</added>
			<value>Nothing new to install.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>active</var_name>
			<added>1255344625</added>
			<value>Active</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>edit_style</var_name>
			<added>1255344633</added>
			<value>Edit Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>export_style</var_name>
			<added>1255344649</added>
			<value>Export Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>are_you_sure</var_name>
			<added>1255344660</added>
			<value>Are you sure?</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>remove_as_default</var_name>
			<added>1255344669</added>
			<value>Remove as Default</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>set_as_default</var_name>
			<added>1255344677</added>
			<value>Set as Default</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>deactivate</var_name>
			<added>1255344683</added>
			<value>Deactivate</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>activate</var_name>
			<added>1255344688</added>
			<value>Activate</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>no_styles_found</var_name>
			<added>1255344698</added>
			<value>No styles found.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>create_a_new_style</var_name>
			<added>1255344704</added>
			<value>Create a New Style</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>logo</var_name>
			<added>1255344710</added>
			<value>Logo</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>select_a_logo</var_name>
			<added>1255344716</added>
			<value>Select a Logo</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>you_can_upload_a_jpg_gif_or_png_file</var_name>
			<added>1255344722</added>
			<value>You can upload a JPG, GIF or PNG file.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>recommended_width_height_width_x_height_pixels</var_name>
			<added>1255344735</added>
			<value>Recommended width/height: {width}x{height} pixels.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>automatically_resize</var_name>
			<added>1255344755</added>
			<value>Automatically Resize</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>current_logo</var_name>
			<added>1255344772</added>
			<value>Current logo</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>revert_logo</var_name>
			<added>1255344804</added>
			<value>Revert Logo</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>upload_logo</var_name>
			<added>1255344818</added>
			<value>Upload Logo</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>template_info</var_name>
			<added>1255344826</added>
			<value>Template Info</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>group</var_name>
			<added>1255344831</added>
			<value>Group</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>global_template</var_name>
			<added>1255344837</added>
			<value>Global Template</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>type</var_name>
			<added>1255344901</added>
			<value>Type</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>block</var_name>
			<added>1255344914</added>
			<value>Block</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>controller</var_name>
			<added>1255344919</added>
			<value>Controller</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>required_only_for_modular_templates</var_name>
			<added>1255344928</added>
			<value>Required only for modular templates.</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>html</var_name>
			<added>1255344940</added>
			<value>HTML</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>html_templates</var_name>
			<added>1255344956</added>
			<value>HTML Templates</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>global_templates</var_name>
			<added>1255344973</added>
			<value>Global Templates</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>controllers</var_name>
			<added>1255344986</added>
			<value>Controllers</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>theme_details</var_name>
			<added>1255345026</added>
			<value>Theme Details</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>folder</var_name>
			<added>1255345049</added>
			<value>Folder</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>export</var_name>
			<added>1255345141</added>
			<value>Export</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>export_styles</var_name>
			<added>1255345208</added>
			<value>Export Styles</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>download</var_name>
			<added>1255345215</added>
			<value>Download</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>manage</var_name>
			<added>1255345751</added>
			<value>Manage</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>edit_theme</var_name>
			<added>1255345761</added>
			<value>Edit Theme</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>edit_templates</var_name>
			<added>1255345771</added>
			<value>Edit Templates</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>manage_styles</var_name>
			<added>1255345779</added>
			<value>Manage Styles</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>recent_visitors</var_name>
			<added>1255345946</added>
			<value>Recent Visitors</value>
		</phrase>
		<phrase>
			<module_id>theme</module_id>
			<version_id>2.0.0rc4</version_id>
			<var_name>default_manage</var_name>
			<added>1255766695</added>
			<value>Default</value>
		</phrase>
	</phrases>
	<sql><![CDATA[a:1:{s:7:"ADD_KEY";a:2:{s:12:"phpfox_theme";a:1:{s:8:"folder_2";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}}s:18:"phpfox_theme_style";a:2:{s:10:"is_default";a:2:{i:0;s:5:"INDEX";i:1;s:10:"is_default";}s:6:"folder";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}}}}]]></sql>
	<update_templates>
		<file type="controller">index.html.php</file>
		<file type="block">design.html.php</file>
	</update_templates>
</upgrade>