<upgrade>
	<settings>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>allow_html_in_activity_feed</var_name>
			<phrase_var_name>setting_allow_html_in_activity_feed</phrase_var_name>
			<ordering>6</ordering>
			<version_id>3.0.0beta3</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>server_settings</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>disable_hash_bang_support</var_name>
			<phrase_var_name>setting_disable_hash_bang_support</phrase_var_name>
			<ordering>14</ordering>
			<version_id>3.0.0beta3</version_id>
			<value>0</value>
		</setting>
	</settings>
	<phpfox_update_settings>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>enabled_edit_area</var_name>
			<phrase_var_name>setting_enabled_edit_area</phrase_var_name>
			<ordering>5</ordering>
			<version_id>2.0.7</version_id>
			<value>0</value>
		</setting>
	</phpfox_update_settings>
	<phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.0.0beta3</version_id>
			<var_name>setting_allow_html_in_activity_feed</var_name>
			<added>1315510132</added>
			<value><![CDATA[<title>Allow HTML in Activity Feed</title><info>If you enable this option it will allow HTML in the activity feed and any comments connected to the feed.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.0.0beta3</version_id>
			<var_name>setting_disable_hash_bang_support</var_name>
			<added>1316512962</added>
			<value><![CDATA[<title>AJAX Browsing - Disable Hash-Bang URL</title><info>If you have "Site Wide AJAX Browsing" enabled we provide support for a function provided with HTML5 that allows the changing of the URL path without actually reloading the page. For browsers that do not have support for this function we use a fallback hash-bang URL. If you do not want to allow the usage of hash-bang URL's enable this option and for browsers that do not have HTML 5 support will not be able to use your sites AJAX browsing functionality. Currently all IE browsers do not have support for this HTML5 function so they by default use the fallback method.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.0.0beta3</version_id>
			<var_name>search_dot</var_name>
			<added>1316530308</added>
			<value>Search...</value>
		</phrase>
	</phrases>
</upgrade>