<upgrade>
	<phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.3.0beta2</version_id>
			<var_name>mobile_search</var_name>
			<added>1340276312</added>
			<value>Search...</value>
		</phrase>
	</phrases>
	<sql><![CDATA[a:1:{s:11:"ALTER_FIELD";a:1:{s:13:"phpfox_search";a:1:{s:12:"search_array";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}}}}]]></sql>
</upgrade>