<upgrade>
	<settings>
		<setting>
			<group>server_settings</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>include_master_files</var_name>
			<phrase_var_name>setting_include_master_files</phrase_var_name>
			<ordering>15</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>defer_loading_user_images</var_name>
			<phrase_var_name>setting_defer_loading_user_images</phrase_var_name>
			<ordering>1</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>defer_loading_images</var_name>
			<phrase_var_name>setting_defer_loading_images</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>keep_non_square_images</var_name>
			<phrase_var_name>setting_keep_non_square_images</phrase_var_name>
			<ordering>3</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>array</type>
			<var_name>controllers_to_load_delayed</var_name>
			<phrase_var_name>setting_controllers_to_load_delayed</phrase_var_name>
			<ordering>4</ordering>
			<version_id>3.6.0rc1</version_id>
			<value><![CDATA[s:8:"array();";]]></value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>super_cache_system</var_name>
			<phrase_var_name>setting_super_cache_system</phrase_var_name>
			<ordering>5</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>store_only_users_in_session</var_name>
			<phrase_var_name>setting_store_only_users_in_session</phrase_var_name>
			<ordering>6</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cdn_content_delivery_network</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>push_jscss_to_cdn</var_name>
			<phrase_var_name>setting_push_jscss_to_cdn</phrase_var_name>
			<ordering>16</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>search_engine_optimization</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>include_site_title_all_pages</var_name>
			<phrase_var_name>setting_include_site_title_all_pages</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>force_404_check</var_name>
			<phrase_var_name>setting_force_404_check</phrase_var_name>
			<ordering>7</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>enable_html_purifier</var_name>
			<phrase_var_name>setting_enable_html_purifier</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>force_secure_site</var_name>
			<phrase_var_name>setting_force_secure_site</phrase_var_name>
			<ordering>1</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>use_custom_cookie_names</var_name>
			<phrase_var_name>setting_use_custom_cookie_names</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>custom_cookie_names_hash</var_name>
			<phrase_var_name>setting_custom_cookie_names_hash</phrase_var_name>
			<ordering>3</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>s6ks763s5h3)s</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>protect_admincp_with_ips</var_name>
			<phrase_var_name>setting_protect_admincp_with_ips</phrase_var_name>
			<ordering>4</ordering>
			<version_id>3.6.0rc1</version_id>
			<value />
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>auth_user_via_session</var_name>
			<phrase_var_name>setting_auth_user_via_session</phrase_var_name>
			<ordering>5</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>include_ip_sub_id_hash</var_name>
			<phrase_var_name>setting_include_ip_sub_id_hash</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>id_hash_salt</var_name>
			<phrase_var_name>setting_id_hash_salt</phrase_var_name>
			<ordering>6</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>iysduyt623rts</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>check_body_for_text</var_name>
			<phrase_var_name>setting_check_body_for_text</phrase_var_name>
			<ordering>7</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>check_body_regex</var_name>
			<phrase_var_name>setting_check_body_regex</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>/oParams/i</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>check_body_offline_message</var_name>
			<phrase_var_name>setting_check_body_offline_message</phrase_var_name>
			<ordering>9</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>Site is under maintenance.</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>check_body_header</var_name>
			<phrase_var_name>setting_check_body_header</phrase_var_name>
			<ordering>10</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>HTTP/1.0 500 Internal Server Error</value>
		</setting>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>large_string</type>
			<var_name>html_purifier_allowed_html</var_name>
			<phrase_var_name>setting_html_purifier_allowed_html</phrase_var_name>
			<ordering>9</ordering>
			<version_id>3.6.0rc1</version_id>
			<value><![CDATA[br,p,em,u,ul,li,font,ol,div[class|style],span[style],blockquote,strike,b,strong,img[src|alt|class|height|width],a[href|rel],iframe[src|width|height|frameborder],object[width|height|data],param[name|value],embed[src|type|allowscriptaccess|allowfullscreen|width|height]]]></value>
		</setting>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>large_string</type>
			<var_name>html_purifier_allowed_iframes</var_name>
			<phrase_var_name>setting_html_purifier_allowed_iframes</phrase_var_name>
			<ordering>10</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>%^http://(www.youtube.com/embed/|player.vimeo.com/video/)%</value>
		</setting>
	</settings>
	<setting_groups>
		<name>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_group_security</var_name>
			<value>security</value>
		</name>
	</setting_groups>
	<phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_include_master_files</var_name>
			<added>1371725536</added>
			<value><![CDATA[<title>JS/CSS Include Master Files</title><info>This setting is designed to create 1 JS and 1 CSS master file so it would only be loaded once by the browser. Then when a user visits a page it will load another file that is specific to that page only. The file will be a lot smaller since it does not have any of the master data.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_defer_loading_user_images</var_name>
			<added>1371725698</added>
			<value><![CDATA[<title>Defer Profile Images</title><info>Load profile images after the site has loaded.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_defer_loading_images</var_name>
			<added>1371725751</added>
			<value><![CDATA[<title>Defer Photos</title><info>Load photos from the Photo module after the site has loaded.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_keep_non_square_images</var_name>
			<added>1371726679</added>
			<value><![CDATA[<title>Keep Non Square Images</title><info>By default we create 2 thumbnails for each image. One keeps the original aspect ratio and the other is a fixed square image. With our current themes we only use the fixed square images. The original aspect ratio images are not really needed and disabling this feature is advised.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_controllers_to_load_delayed</var_name>
			<added>1371726829</added>
			<value><![CDATA[<title>Load sections via AJAX</title><info>You can define an array of controllers that will be loaded after the site has been loaded via AJAX.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_super_cache_system</var_name>
			<added>1371727047</added>
			<value><![CDATA[<title>Global Caching</title><info>Global caching setting. Enable to turn on caching system on several areas. Drops database queries.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_store_only_users_in_session</var_name>
			<added>1371732076</added>
			<value><![CDATA[<title>Only Users in Session Table</title><info>Only store users in the session table. Keeps bots and guests out from this table.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_push_jscss_to_cdn</var_name>
			<added>1371732268</added>
			<value><![CDATA[<title>Upload CSS/JS to CDN</title><info>Upload minified CSS/JS to CDN if minified files is enabled. Note you will still need to manually upload your themes images. This only works for CSS and JavaScript files.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_include_site_title_all_pages</var_name>
			<added>1371732664</added>
			<value><![CDATA[<title>Remove Site Title</title><info>Removes site title on all pages other then the index page and if a page has no title. This is to assist with duplicate content.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_force_404_check</var_name>
			<added>1371732723</added>
			<value><![CDATA[<title>Force 404 Check</title><info>Enable to force 404 checks on sub-pages that do not exist. This works in selective sections.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_enable_html_purifier</var_name>
			<added>1371733020</added>
			<value><![CDATA[<title>HTML PURIFIER</title><info>If enabled we will use a 3rd party library to assist in parsing content submitted by your users. Only enable this if you allow HTML on your site. To learn more about this product check out:
http://htmlpurifier.org/

You can find additional settings in the file:
include/setting/htmlpurifier.sett.php.new</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_group_security</var_name>
			<added>1371733071</added>
			<value><![CDATA[<title>Security</title><info>Manage security settings for your site.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_force_secure_site</var_name>
			<added>1371733146</added>
			<value><![CDATA[<title>Force HTTS for Logged In Users</title><info>Enable to make all connections secure when a user is logged in. <b>Notice:</b> Your server must have HTTPS support.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_use_custom_cookie_names</var_name>
			<added>1371733182</added>
			<value><![CDATA[<title>Custom Cookie Names</title><info>Enable to use custom cookie names</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_custom_cookie_names_hash</var_name>
			<added>1371733247</added>
			<value><![CDATA[<title>Custom Cookie Name Unique Salt</title><info>Create your own unique cookie name salt.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_protect_admincp_with_ips</var_name>
			<added>1371733289</added>
			<value><![CDATA[<title>AdminCP IP Access</title><info>Allow access to the AdminCP if an IP is added to this list. Comma separated.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_auth_user_via_session</var_name>
			<added>1371733504</added>
			<value><![CDATA[<title>Authenticate Users via Satabase Session Log</title><info>If you enable this option we will authenticate users via a database session log.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_include_ip_sub_id_hash</var_name>
			<added>1371733576</added>
			<value><![CDATA[<title>User IP Substring in ID Hash</title><info>Enable to include a users IP substring in the ID hash. This makes it much harder for users to hijack another users session.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_id_hash_salt</var_name>
			<added>1371733619</added>
			<value><![CDATA[<title>Unique Salt for ID Hash</title><info>Create your own unique hash for the authenticating ID hash.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_check_body_for_text</var_name>
			<added>1371733697</added>
			<value><![CDATA[<title>HTML Body Check</title><info>Enable to check HTML body for specific text.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_check_body_regex</var_name>
			<added>1371733742</added>
			<value><![CDATA[<title>HTML Body Check REGEX</title><info>Add your custom REGEX to check the HTML body.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_check_body_offline_message</var_name>
			<added>1371733838</added>
			<value><![CDATA[<title>HTML Body Check Failed Message</title><info>If the REGEX check fails, add a message we should display.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_check_body_header</var_name>
			<added>1371733888</added>
			<value><![CDATA[<title>HTML Body Check Failed Response</title><info>Custom header to send the browser in case the HTML body check REGEX fails.</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_html_purifier_allowed_html</var_name>
			<added>1371734080</added>
			<value><![CDATA[<title>HTML PURIFIER Allowed HTML</title><info>Comma separated list of HTML elements and attributes HTML Purifier should allow.

To learn more on how this setting works check out:
http://htmlpurifier.org/live/configdoc/plain.html#HTML.Allowed</info>]]></value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_html_purifier_allowed_iframes</var_name>
			<added>1371734180</added>
			<value><![CDATA[<title>HTML PURIFIER Allowed IFRAMES REGEX</title><info>REGEX of sites HTML Purifier should allow when users use HTML IFRAMES.</info>]]></value>
		</phrase>
	</phrases>
	<phpfox_update_phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.5.0beta1</version_id>
			<var_name>setting_keep_files_in_server</var_name>
			<added>1353415860</added>
			<value><![CDATA[<title>Keep Files In Server</title><info>Set this to TRUE to keep all the files on the server after they have been uploaded to your CDN.</info>]]></value>
		</phrase>
	</phpfox_update_phrases>
</upgrade>