<upgrade>
	<phpfox_update_settings>
		<setting>
			<group>debug</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>drop</type>
			<var_name>admin_debug_mode</var_name>
			<phrase_var_name>setting_admin_debug_mode</phrase_var_name>
			<ordering>1</ordering>
			<version_id>2.0.0alpha1</version_id>
			<value><![CDATA[a:2:{s:7:"default";s:7:"level_0";s:6:"values";a:4:{i:0;s:7:"level_0";i:1;s:7:"level_1";i:2;s:7:"level_2";i:3;s:7:"level_3";}}]]></value>
		</setting>
	</phpfox_update_settings>
	<phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>text</var_name>
			<added>1392649453</added>
			<value>Text</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>top_left</var_name>
			<added>1392649827</added>
			<value>top left</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>bottom_left</var_name>
			<added>1392649851</added>
			<value>bottom left</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>bottom_right</var_name>
			<added>1392649867</added>
			<value>bottom right</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>top_right</var_name>
			<added>1392649881</added>
			<value>top right</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>rackspace</var_name>
			<added>1392650017</added>
			<value>Rackspace</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>phpfox</var_name>
			<added>1392650024</added>
			<value>PHPFox</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>s3</var_name>
			<added>1392650034</added>
			<value>Amazon S3</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>tiny_mce</var_name>
			<added>1392650096</added>
			<value>TinyMCE</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>default</var_name>
			<added>1392650104</added>
			<value>Default</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>level_0</var_name>
			<added>1392650441</added>
			<value>Level 0</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>level_1</var_name>
			<added>1392650455</added>
			<value>Level 1</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>level_2</var_name>
			<added>1392650461</added>
			<value>Level 2</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>level_3</var_name>
			<added>1392650469</added>
			<value>Level 3</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>mail</var_name>
			<added>1392650630</added>
			<value>mail</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>smtp</var_name>
			<added>1392650636</added>
			<value>smtp</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>medium</var_name>
			<added>1392735559</added>
			<value>medium</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>high</var_name>
			<added>1392735577</added>
			<value>high</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>low</var_name>
			<added>1392735581</added>
			<value>low</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>mdy</var_name>
			<added>1392813730</added>
			<value>MDY</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>dmy</var_name>
			<added>1392813736</added>
			<value>DMY</value>
		</phrase>
		<phrase>
			<module_id>core</module_id>
			<version_id>3.7.5</version_id>
			<var_name>ymd</var_name>
			<added>1392813745</added>
			<value>YMD</value>
		</phrase>
	</phrases>
</upgrade>