<upgrade>
	<phpfox_update_settings>
		<setting>
			<group />
			<module_id>facebook</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>facebook_like_event</var_name>
			<phrase_var_name>setting_facebook_like_event</phrase_var_name>
			<ordering>9</ordering>
			<version_id>2.0.5dev1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group />
			<module_id>facebook</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>facebook_like_group</var_name>
			<phrase_var_name>setting_facebook_like_group</phrase_var_name>
			<ordering>8</ordering>
			<version_id>2.0.5dev1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group />
			<module_id>facebook</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>facebook_like_video</var_name>
			<phrase_var_name>setting_facebook_like_video</phrase_var_name>
			<ordering>7</ordering>
			<version_id>2.0.5dev1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group />
			<module_id>facebook</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>facebook_like_photo</var_name>
			<phrase_var_name>setting_facebook_like_photo</phrase_var_name>
			<ordering>6</ordering>
			<version_id>2.0.5dev1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group />
			<module_id>facebook</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>facebook_like_blog</var_name>
			<phrase_var_name>setting_facebook_like_blog</phrase_var_name>
			<ordering>5</ordering>
			<version_id>2.0.5dev1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group>facebook_connect</group>
			<module_id>facebook</module_id>
			<is_hidden>1</is_hidden>
			<type>string</type>
			<var_name>facebook_api_key</var_name>
			<phrase_var_name>setting_facebook_api_key</phrase_var_name>
			<ordering>2</ordering>
			<version_id>2.0.4</version_id>
			<value />
		</setting>
		<setting>
			<group />
			<module_id>facebook</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>facebook_like_marketplace</var_name>
			<phrase_var_name>setting_facebook_like_marketplace</phrase_var_name>
			<ordering>10</ordering>
			<version_id>2.0.5dev1</version_id>
			<value>1</value>
		</setting>
	</phpfox_update_settings>
</upgrade>