<upgrade>
	<phrases>
		<phrase>
			<module_id>apps</module_id>
			<version_id>3.4.0</version_id>
			<var_name>admincp_menu_apps</var_name>
			<added>1351240933</added>
			<value>Apps</value>
		</phrase>
		<phrase>
			<module_id>apps</module_id>
			<version_id>3.4.0</version_id>
			<var_name>install_app</var_name>
			<added>1351241071</added>
			<value>Install App</value>
		</phrase>
		<phrase>
			<module_id>apps</module_id>
			<version_id>3.4.0</version_id>
			<var_name>export_apps</var_name>
			<added>1351241088</added>
			<value>Export Apps</value>
		</phrase>
	</phrases>
	<phpfox_update_phrases>
		<phrase>
			<module_id>apps</module_id>
			<version_id>3.4.0</version_id>
			<var_name>admin_menu_categories</var_name>
			<added>1351240790</added>
			<value>Categories</value>
		</phrase>
	</phpfox_update_phrases>
</upgrade>