<upgrade>
	<phpfox_update_settings>
		<setting>
			<group>server_settings</group>
			<module_id>core</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>load_jquery_from_google_cdn</var_name>
			<phrase_var_name>setting_load_jquery_from_google_cdn</phrase_var_name>
			<ordering>11</ordering>
			<version_id>2.1.0Beta1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>server_settings</group>
			<module_id>core</module_id>
			<is_hidden>1</is_hidden>
			<type>string</type>
			<var_name>jquery_google_cdn_version</var_name>
			<phrase_var_name>setting_jquery_google_cdn_version</phrase_var_name>
			<ordering>12</ordering>
			<version_id>2.1.0Beta1</version_id>
			<value>1.4.4</value>
		</setting>
		<setting>
			<group>server_settings</group>
			<module_id>core</module_id>
			<is_hidden>1</is_hidden>
			<type>string</type>
			<var_name>jquery_ui_google_cdn_version</var_name>
			<phrase_var_name>setting_jquery_ui_google_cdn_version</phrase_var_name>
			<ordering>13</ordering>
			<version_id>2.1.0Beta1</version_id>
			<value>1.8.7</value>
		</setting>
	</phpfox_update_settings>
	<phpfox_update_phrases>
		<phrase>
			<module_id>core</module_id>
			<version_id>2.1.0Beta1</version_id>
			<var_name>setting_friends_only_community</var_name>
			<added>1293613541</added>
			<value><![CDATA[<title>Friends Only Community</title><info>By enabling this option certain sections (eg. Blogs, Photos etc...), will by default only show items from the member and his or her friends list. <b>Note:</b> In order for this to work you must enable the option <b>Section Privacy Item Browsing
</b></info>]]></value>
		</phrase>
	</phpfox_update_phrases>
</upgrade>