<upgrade>
	<phrases>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>package_successfully_updated</var_name>
			<added>1254388768</added>
			<value>Package successfully updated.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>package_successfully_added</var_name>
			<added>1254388782</added>
			<value>Package successfully added.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>edit_package</var_name>
			<added>1254388798</added>
			<value>Edit Package</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>add_package</var_name>
			<added>1254388814</added>
			<value>Add Package</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>package_successfully_deleted</var_name>
			<added>1254388860</added>
			<value>Package successfully deleted.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>emoticon_successfully_deleted</var_name>
			<added>1254388893</added>
			<value>Emoticon successfully deleted.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>emoticon_successfully_updated</var_name>
			<added>1254388906</added>
			<value>Emoticon successfully updated.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>emoticon_successfully_added</var_name>
			<added>1254388920</added>
			<value>Emoticon successfully added.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>edit_emoticon</var_name>
			<added>1254388930</added>
			<value>Edit Emoticon</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>add_emoticon</var_name>
			<added>1254388967</added>
			<value>Add Emoticon</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>emoticon_package_successfully_created</var_name>
			<added>1254389056</added>
			<value>Emoticon package successfully created. Imported: {success} - Failed: {failed}</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>import_emoticons</var_name>
			<added>1254389088</added>
			<value>Import Emoticons</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>package_does_not_exist</var_name>
			<added>1254389236</added>
			<value>Package does not exist.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>emoticons_successfully_updated</var_name>
			<added>1254389246</added>
			<value>Emoticons successfully updated.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>view_emoticon_package</var_name>
			<added>1254389255</added>
			<value>View Emoticon Package</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>view_package</var_name>
			<added>1254389277</added>
			<value>View Package</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>emoticon_package_not_found</var_name>
			<added>1254389313</added>
			<value>Emoticon package not found.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>select_a_module</var_name>
			<added>1254389331</added>
			<value>Select a module.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>provide_a_emoticon_symbol</var_name>
			<added>1254389381</added>
			<value>Provide a emoticon symbol.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>define_a_path_for_the_package</var_name>
			<added>1254389405</added>
			<value>Define a path for the package.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>symbol_already_exists</var_name>
			<added>1254389419</added>
			<value>Symbol already exists.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>image_could_not_be_uploaded</var_name>
			<added>1254389432</added>
			<value>Image could not be uploaded.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>please_fill_in_the_package_name_field</var_name>
			<added>1254389445</added>
			<value>Please fill in the package name field.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>path_is_not_writable_and_the_folder_could_not_be_created</var_name>
			<added>1254389476</added>
			<value>{path} is not writable and the folder could not be created.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>not_a_valid_emoticon_package</var_name>
			<added>1254389502</added>
			<value>Not a valid emoticon package.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>unable_to_import_emoticon_package</var_name>
			<added>1254389512</added>
			<value>Unable to import emoticon package.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>name</var_name>
			<added>1254389561</added>
			<value>Name</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>mass_import</var_name>
			<added>1254389571</added>
			<value>Mass Import</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>you_can_optionally_mass_import_emoticons_from_a_zip_package</var_name>
			<added>1254389591</added>
			<value>You can optionally mass import emoticons from a ZIP package. All emoticons must be located within the root directory of the ZIP package in order for a successful import.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>add</var_name>
			<added>1254389619</added>
			<value>Add</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>package_details</var_name>
			<added>1254389637</added>
			<value>Package Details</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>packages</var_name>
			<added>1254389649</added>
			<value>Packages</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>active</var_name>
			<added>1254389668</added>
			<value>Active</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>view_emoticons</var_name>
			<added>1254389677</added>
			<value>View Emoticons</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>export_package</var_name>
			<added>1254389696</added>
			<value>Export Package</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>delete_package</var_name>
			<added>1254389704</added>
			<value>Delete Package</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>are_you_sure</var_name>
			<added>1254389714</added>
			<value>Are you sure?</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>deactivate</var_name>
			<added>1254389727</added>
			<value>Deactivate</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>activate</var_name>
			<added>1254389733</added>
			<value>Activate</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>no_emoticons_in_this_package</var_name>
			<added>1254389744</added>
			<value>No emoticons in this package.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>emoticon_details</var_name>
			<added>1254389762</added>
			<value>Emoticon Details</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>package</var_name>
			<added>1254389776</added>
			<value>Package</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>image</var_name>
			<added>1254389788</added>
			<value>Image</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>title</var_name>
			<added>1254389795</added>
			<value>Title</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>symbol</var_name>
			<added>1254389802</added>
			<value>Symbol</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>edit</var_name>
			<added>1254389813</added>
			<value>Edit</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>import</var_name>
			<added>1254389831</added>
			<value>Import</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>file</var_name>
			<added>1254389839</added>
			<value>File</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>zip_package_only_and_must_have_a_similar_name_structure</var_name>
			<added>1254389853</added>
			<value><![CDATA[ZIP package only and must have a similar name structure: phpfox-emoticon-<i>packagename</i>.zip]]></value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>overwrite</var_name>
			<added>1254389861</added>
			<value>Overwrite</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>yes</var_name>
			<added>1254389868</added>
			<value>Yes</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>no</var_name>
			<added>1254389874</added>
			<value>No</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>delete_emoticon</var_name>
			<added>1254389940</added>
			<value>Delete Emoticon</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>this_package_contains_no_emoticons</var_name>
			<added>1254389956</added>
			<value>This package contains no emoticons.</value>
		</phrase>
		<phrase>
			<module_id>emoticon</module_id>
			<version_id>2.0.0rc3</version_id>
			<var_name>update</var_name>
			<added>1254389964</added>
			<value>Update</value>
		</phrase>
	</phrases>
</upgrade>